import { Character } from "./character.model";

export const mockCharacters: Character[] = [{
    id: '1',
    name: 'Luke Skywalker',
    birth_year: '19BBY',
    eye_color: 'Blue',
    gender: 'Male',
    hair_color: 'Blond',
    height: 172,
    mass: 77,
    skin_color: 'Fair',
    homeworld: 'Tatooine',
    films: [
      'https://swapi.dev/api/films/1/',
      'https://swapi.dev/api/films/2/',
      'https://swapi.dev/api/films/3/',
    ],
    species: ['https://swapi.dev/api/species/1/'],
    starships: [
      'https://swapi.dev/api/starships/12/',
      'https://swapi.dev/api/starships/22/',
    ],
    vehicles: ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'],
    created: new Date('2014-12-09T13:50:51.644000Z'),
    edited: new Date('2014-12-20T21:17:56.891000Z'),
    url: 'https://swapi.dev/api/people/1/',
  },
  {
    id: '2',
    name: 'Luke Skywalker',
    birth_year: '19BBY',
    eye_color: 'Blue',
    gender: 'Male',
    hair_color: 'Blond',
    height: 172,
    mass: 77,
    skin_color: 'Fair',
    homeworld: 'Tatooine',
    films: [
      'https://swapi.dev/api/films/1/',
      'https://swapi.dev/api/films/2/',
      'https://swapi.dev/api/films/3/',
    ],
    species: ['https://swapi.dev/api/species/1/'],
    starships: [
      'https://swapi.dev/api/starships/12/',
      'https://swapi.dev/api/starships/22/',
    ],
    vehicles: ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'],
    created: new Date('2014-12-09T13:50:51.644000Z'),
    edited: new Date('2014-12-20T21:17:56.891000Z'),
    url: 'https://swapi.dev/api/people/1/',
  },
  {
    name: 'Luke Skywalker',
    films: [
      'https://swapi.dev/api/films/1',
      'https://swapi.dev/api/films/2',
    ],
    id: '',
    birth_year: '',
    eye_color: '',
    gender: '',
    hair_color: '',
    height: 0,
    mass: 0,
    skin_color: '',
    homeworld: '',
    species: [],
    starships: [],
    vehicles: [],
    created: new Date(),
    edited: new Date(),
    url: ''
  }]